export const supportedCryptos = [
  { symbol: 'BTC', name: 'Bitcoin' },
  { symbol: 'ETH', name: 'Ethereum' },
  { symbol: 'BNB', name: 'Binance Coin' },
  { symbol: 'SOL', name: 'Solana' },
  { symbol: 'XRP', name: 'Ripple' },
  { symbol: 'ADA', name: 'Cardano' },
  { symbol: 'AVAX', name: 'Avalanche' },
  { symbol: 'DOGE', name: 'Dogecoin' },
  { symbol: 'DOT', name: 'Polkadot' },
  { symbol: 'LINK', name: 'Chainlink' },
  { symbol: 'UNI', name: 'Uniswap' },
  { symbol: 'ATOM', name: 'Cosmos' },
  { symbol: 'LTC', name: 'Litecoin' },
  { symbol: 'OP', name: 'Optimism' },
  { symbol: 'XLM', name: 'Stellar' },
  { symbol: 'NEAR', name: 'NEAR Protocol' },
  { symbol: 'ICP', name: 'Internet Computer' },
  { symbol: 'BCH', name: 'Bitcoin Cash' },
  { symbol: 'INJ', name: 'Injective' },
  { symbol: 'FIL', name: 'Filecoin' },
  { symbol: 'VET', name: 'VeChain' },
  { symbol: 'ALGO', name: 'Algorand' },
  { symbol: 'GRT', name: 'The Graph' },
  { symbol: 'AAVE', name: 'Aave' },
  { symbol: 'QNT', name: 'Quant' },
  { symbol: 'THETA', name: 'Theta Network' },
  { symbol: 'FLOW', name: 'Flow' },
  { symbol: 'AXS', name: 'Axie Infinity' }
];